### PR TITLE
Poll immediately on page focus

### PR DESCRIPTION
**Pull request by sandersky**
# MINOR

### CODE REVIEW

**Comment by sandersky** [comment]
:+1:

**Comment by sglanzer-fire** [comment]
Approved - any thoughts on integration http://ember-concurrency.com/#/docs with this?

[Approved with PullApprove](https://pullapprove.com/ciena-blueplanet/ember-pollboy/pull-request/9/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-blueplanet/ember-pollboy)

**Comment by sandersky** [comment]
Not sure what we really gain with that @sglanzer

**Comment by sglanzer-fire** [comment]
Looks very similar to what we need (task iteration/cancellation) and comes with a few nifty features.  Not mandatory, just thought it might be worth a look.

**Pull request merged**
